% Generated by ChatGPT
figure;
axis equal;
grid on;
hold on;
view(3);

% Debugging variable
use_wrapping = true;

R_humerus = system_params.Rhum;

% Draw sphere once
[Xs, Ys, Zs] = sphere(30);
surf(R_humerus*Xs, R_humerus*Ys, R_humerus*Zs, ...
    'FaceAlpha', 0.1, 'EdgeColor', 'none');

fields = fieldnames(system_params.cables);
colors = lines(numel(fields));


data = out.quaternion_all_states.Data;
n_steps = size(data, 3);


eps_wrap = 1e-4;

p_wrap_prev = ones(3,7);


%for k = 1:length(q_hist)
for k = 1:n_steps

    cla; % clear frame
    hold on;

    % redraw sphere
    surf(R_humerus*Xs, R_humerus*Ys, R_humerus*Zs, ...
        'FaceAlpha', 0.1, 'EdgeColor', 'none');

    %q = q_hist(k, :);
    q = squeeze(data(1:4, 1, k))';  % row vector [1x4]
    %q = [q(4), q(1), q(2), q(3)]; % reorder
    R = quat2rotm(q);

    for i = 1:numel(fields)
        cable = system_params.cables.(fields{i});

        % Points
        p_humerus = R * cable.L;
        p_scapula = cable.M;

        % === WRAPPING LOGIC (same as simulation) ===
        ri = p_humerus;
        di = p_scapula - ri;

        n = di' * p_humerus;
        d = di' * di;
        t_star = -n / d;

        p_closest = p_humerus + t_star * di;
        p_norm = norm(p_closest);
        % define plane normal
        n = cross(p_humerus, p_scapula);
        
        if norm(n) < 1e-8
            % fallback to previous wrap
            p_wrap = p_wrap_prev(:,i);
        else
            n_hat = n / norm(n);
        
            % project closest point onto plane
            x_plane = p_closest - dot(p_closest, n_hat) * n_hat;
        
            if norm(x_plane) < 1e-8
                p_wrap = p_wrap_prev(:,i);
            else
                dir = x_plane / norm(x_plane);
                p_wrap = R_humerus * dir;
            end
        end

        if p_norm < R_humerus && t_star > 0 && t_star < 1 && use_wrapping
    
            % % Her e kanskje noke bullshit
            % if p_norm < eps_wrap
            %     dir = p_wrap_prev(:,i) / norm(p_wrap_prev(:,i));
            % else
            %     dir_new = p_closest / p_norm;
            %     dir_old = p_wrap_prev(:,i) / norm(p_wrap_prev(:,i));
            % 
            %     alpha = p_norm / (p_norm + eps_wrap);
            %     dir = alpha * dir_new + (1 - alpha) * dir_old;
            %     dir = dir / norm(dir);
            % end
            % 
            % p_wrap = R_humerus * dir;
            % p_wrap_prev(:,i) = p_wrap;
            % % Her slutta bullshit

            % wrapping point
            %p_wrap = p_closest / p_norm * R_humerus;

            % half-space constraint
            v = cable.v;
            % if dot(p_wrap, v) < 0
            %     p_wrap = -p_wrap;
            % end
            if dot(p_wrap, v) < -1e-6
                p_wrap = p_wrap - 2 * dot(p_wrap, v) * v;
            end

            % draw two segments
            plot3([p_humerus(1) p_wrap(1)], ...
                  [p_humerus(2) p_wrap(2)], ...
                  [p_humerus(3) p_wrap(3)], ...
                  'Color', colors(i,:), 'LineWidth', 2);

            plot3([p_wrap(1) p_scapula(1)], ...
                  [p_wrap(2) p_scapula(2)], ...
                  [p_wrap(3) p_scapula(3)], ...
                  'Color', colors(i,:), 'LineWidth', 2);

            % draw wrap point
            plot3(p_wrap(1), p_wrap(2), p_wrap(3), 'o', ...
                'Color', colors(i,:), 'MarkerSize', 6, 'MarkerFaceColor', colors(i,:));

        else
            % straight cable
            plot3([p_humerus(1) p_scapula(1)], ...
                  [p_humerus(2) p_scapula(2)], ...
                  [p_humerus(3) p_scapula(3)], ...
                  'Color', colors(i,:), 'LineWidth', 2);
        end

        % draw endpoints
        plot3(p_humerus(1), p_humerus(2), p_humerus(3), 'k.', 'MarkerSize', 15);
        plot3(p_scapula(1), p_scapula(2), p_scapula(3), 'r.', 'MarkerSize', 15);

    end

    xlabel('X'); ylabel('Y'); zlabel('Z');
    title(sprintf('Frame %d', k));

    drawnow;
end
