% Generated by ChatGPT

figure;
axis equal;
grid on;
hold on;
view(3);

% Toggle wrapping
use_wrapping = true;

R_humerus = system_params.Rhum;

% Draw sphere once (template)
[Xs, Ys, Zs] = sphere(30);

fields = fieldnames(system_params.cables);
n_cables = numel(fields);
colors = lines(n_cables);

data = out.quaternion_all_states.Data;
n_steps = size(data, 3);

eps_small = 1e-8;

% Initialize previous wrap points (safe non-zero directions)
p_wrap_prev = repmat([0;0;1], 1, n_cables);

for k = 1:n_steps

    cla;
    hold on;

    % Draw sphere
    surf(R_humerus*Xs, R_humerus*Ys, R_humerus*Zs, ...
        'FaceAlpha', 0.1, 'EdgeColor', 'none');

    % Extract quaternion
    q = squeeze(data(1:4, 1, k))';
    % q = [q(4), q(1), q(2), q(3)]; % uncomment if needed
    R = quat2rotm(q);

    for i = 1:n_cables

        cable = system_params.cables.(fields{i});

        % Points
        p_humerus = R * cable.L;
        p_scapula = cable.M;

        ri = p_humerus;
        di = p_scapula - ri;

        % Closest point on line
        d = di' * di;
        if d < eps_small
            t_star = 0;
        else
            n_line = di' * p_humerus;
            t_star = -n_line / d;
        end

        p_closest = p_humerus + t_star * di;
        p_norm = norm(p_closest);

        % === WRAPPING ===
        if use_wrapping && p_norm < R_humerus && t_star > 0 && t_star < 1

            % --- Define plane ---
            n_plane = cross(p_humerus, p_scapula);

            if norm(n_plane) < eps_small
                % fallback to previous
                p_wrap = p_wrap_prev(:,i);
            else
                n_hat = n_plane / norm(n_plane);

                % project onto plane
                x_plane = p_closest - dot(p_closest, n_hat) * n_hat;

                if norm(x_plane) < eps_small
                    % fallback
                    p_wrap = p_wrap_prev(:,i);
                else
                    dir = x_plane / norm(x_plane);
                    p_wrap = R_humerus * dir;
                end
            end

            % --- Half-space constraint (reflection) ---
            v_hat = cable.v / norm(cable.v);

            if dot(p_wrap, v_hat) < -1e-6
                p_wrap = p_wrap - 2 * dot(p_wrap, v_hat) * v_hat;
            end

            % store for next timestep
            p_wrap_prev(:,i) = p_wrap;

            % --- Plot wrapped cable ---
            plot3([p_humerus(1) p_wrap(1)], ...
                  [p_humerus(2) p_wrap(2)], ...
                  [p_humerus(3) p_wrap(3)], ...
                  'Color', colors(i,:), 'LineWidth', 2);

            plot3([p_wrap(1) p_scapula(1)], ...
                  [p_wrap(2) p_scapula(2)], ...
                  [p_wrap(3) p_scapula(3)], ...
                  'Color', colors(i,:), 'LineWidth', 2);

            plot3(p_wrap(1), p_wrap(2), p_wrap(3), 'o', ...
                'Color', colors(i,:), 'MarkerSize', 6, ...
                'MarkerFaceColor', colors(i,:));

        else
            % --- Straight cable ---
            plot3([p_humerus(1) p_scapula(1)], ...
                  [p_humerus(2) p_scapula(2)], ...
                  [p_humerus(3) p_scapula(3)], ...
                  'Color', colors(i,:), 'LineWidth', 2);
        end

        % Endpoints
        plot3(p_humerus(1), p_humerus(2), p_humerus(3), ...
            'k.', 'MarkerSize', 15);

        plot3(p_scapula(1), p_scapula(2), p_scapula(3), ...
            'r.', 'MarkerSize', 15);

    end

    xlabel('X'); ylabel('Y'); zlabel('Z');
    title(sprintf('Frame %d', k));

    drawnow;
end