%Generated by ChatGPT

function theta = quaternion_to_euler(q)
q = q / norm(q);

q0 = q(1); q1 = q(2); q2 = q(3); q3 = q(4);

A = atan2(2*(q0*q1 + q2*q3), ...
            1 - 2*(q1^2 + q2^2));

sin_B = 2*(q0*q2 - q3*q1);

% Clamp to avoid numerical issues
sin_B = max(min(sin_B, 1), -1);

B = asin(sin_B);

C = atan2(2*(q0*q3 + q1*q2), ...
            1 - 2*(q2^2 + q3^2));

theta = [A; B; C];
end