% Generated by ChatGPT
function theta = tranmat2euler(T)
    % Returns [roll; pitch; yaw]
    R = T(1:3, 1:3);

    if abs(R(1,3)) < 1
        pitch = asin(R(1,3));
        roll  = atan2(-R(2,3), R(3,3));
        yaw   = atan2(-R(1,2), R(1,1));
    else
        % Gimbal lock
        pitch = pi/2 * sign(R(1,3));
        roll  = atan2(R(3,2), R(2,2));
        yaw   = 0;
    end

    theta = [roll; pitch; yaw];
end