function [Ad,Bd] = linearize(x,u,Ts)
% Generated by ChatGPT
n = length(x); m = length(u);
Ad = zeros(n,n);
Bd = zeros(n,m);

x_dl = dlarray(x);
u_dl = dlarray(u);

f_map = @(x,u) runge_kutta4(x, u, Ts);

x_next = f_map(x_dl,u_dl);

for i = 1:n
    grad_i = dlgradient(x_next(i), x_dl, 'EnableHigherDerivatives', true);
    Ad(i,:) = extractdata(grad_i)';
    grad_i = dlgradient(x_next(i), u_dl, 'EnableHigherDerivatives', true);
    Bd(i,:) = extractdata(grad_i)';
end
end